Resources:
  QueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: QueueTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  TasksQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: TasksQueue

  CsvDirectory:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: csv-directory